<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OEVFJIS" failures="1" tests="1" name="Admin_Edit_UpdateTime" time="309.897" errors="0" timestamp="2023-05-17T13:34:50 GMT-04:00">
  <testcase classname="All_TestClasses.TestAdmin_EditTime_UpdateSameTime" name="Admin_Edit_UpdateTime" time="234.393">
    <failure type="java.lang.AssertionError" message="expected [Booking status updated successfully]] but found [Booking status updated successfully]">
      <![CDATA[java.lang.AssertionError: expected [Booking status updated successfully]] but found [Booking status updated successfully]
at All_TestClasses.TestAdmin_EditTime_UpdateSameTime.Admin_Edit_UpdateTime(TestAdmin_EditTime_UpdateSameTime.java:263)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Admin_Edit_UpdateTime -->
</testsuite> <!-- Admin_Edit_UpdateTime -->
